name: WildFly microprofile-reactive-messaging-kafka Quickstart CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'microprofile-reactive-messaging-kafka/**'
      - '.github/workflows/quickstart_ci.yml'
jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: microprofile-reactive-messaging-kafka
      TEST_BOOTABLE_JAR: true
      # See https://issues.redhat.com/browse/WFLY-18676 for why we are excluding this on Windows for now.
      MATRIX_OS: '"ubuntu-20.04"'