name: WildFly jta-crash-rec Quickstart CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - jta-crash-rec/**'
      - .github/workflows/quickstart_ci.yml

jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: jta-crash-rec
      TEST_OPENSHIFT: false