name: WildFly ejb-throws-exception Quickstart CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'ejb-throws-exception/**'
      - '.github/workflows/quickstart_ci.yml'

jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: ejb-throws-exception
      DEPLOYMENT_DIR: ear
      TEST_PROVISIONED_SERVER: true
      TEST_OPENSHIFT: false
      MVN_COMMAND: install