name: WildFly http-custom-mechanism Quickstart CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'http-custom-mechanism/**'
      - .github/workflows/quickstart_ci.yml

jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: http-custom-mechanism
      DEPLOYMENT_DIR: webapp
      TEST_PROVISIONED_SERVER: true
      TEST_OPENSHIFT: false