name: WildFly ejb-security-context-propagation Quickstart CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'ejb-security-context-propagation/**'
      - '.github/workflows/quickstart_ci.yml'

jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: ejb-security-context-propagation
      TEST_PROVISIONED_SERVER: true
      TEST_OPENSHIFT: false