name: WildFly jts Quickstart CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - jts/**'
      - .github/workflows/quickstart_ci.yml

jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: jts
      TEST_PROVISIONED_SERVER: false
      TEST_OPENSHIFT: false
