name: WildFly servlet-filterlistener Quickstart CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'servlet-filterlistener/**'
      - '.github/workflows/quickstart_ci.yml'
jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: servlet-filterlistener
      TEST_PROVISIONED_SERVER: true
